livereload: true

# Site settings
title: "Adrián Mato – Designer at XBOX, leading developer & creator tools"
description: "Designing & building tools for developers at XBOX. Startup investor."
email: hello@adrianmato.com
baseurl: "" # the subpath of your site, e.g. /blog
baseurl_blog: "/blog" # the subpath of the blog
url: "https://adrianmato.com" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Adrián Mato
  twitter: adrianmg
twitter:
  username: adrianmg
  card: summary_large_image
bluesky: adrianmato.com
linkedin: adrianmg
github: adrianmg
instagram: adrianmato

# Custom Settings
timezone: America/Los_Angeles
permalink: /:categories/:title/

# Page defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      image:
        path: /assets/og-image.png?v=2
        width: 1200
        height: 600

# Build settings
markdown: kramdown
incremental: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - netlify
  - netlify.toml
  - package.json
  - package-lock.json
  - scripts
include:
  - 404.html
